### PR TITLE
refactor(experimental): fix linting errors

### PR DESCRIPTION
**Pull request by lorisleiva**
Fixes linting errors introduced in previous PRs of this stack.

### CODE REVIEW

**Comment by lorisleiva** [comment]
CI should cancel itself when we merge multiple in a row, right?

I can revert and update each PR individually but that created lot's of irrelevant conflicts so thought it'd be quicker to have a PR that fixes everything at the end.

**Comment by buffalojoec** [comment]
> CI should cancel itself when we merge multiple in a row, right?

Yeah but I'm not super confident in the timing of each abort. It might manage to get a few packages off before terminating.

I wish Graphite had support for a "squashed merge".

**Comment by steveluscher** [comment]
`gt feedback "..."`

**Comment by steveluscher** [comment]
Ordinarily I'd say the same thing (revertability, atomicity, etc) but in this case I don't think it's a big deal.

You _literally_ can do this with one command though.

```shell
gt co loris/errors-double-underscore
git rebase --interactive --exec "pnpm style:fix" master
```

**Review by steveluscher — APPROVED** [review]

**Comment by lorisleiva** [comment]
Hmm sorry this didn't work for me. After running this, I checked at the first branch that was supposed to be fixed yet the import order was still not alphabetically sorted. 😕 

I think it's much easier to just merge the whole stack personally.

**Comment by steveluscher** [comment]
> After running this, I checked at the first branch that was supposed to be fixed yet the import order was still not alphabetically sorted.

I updated the command in the comment.

**Comment by lorisleiva** [comment]
Yeah that was with the latest version I'm afraid.

**Comment by steveluscher** [comment]
### Merge activity

* **Mar 5, 10:18 AM PST**: @steveluscher started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2265).

**Pull request merged**
