### PR TITLE
refactor(experimental): align program account types with account types

### PR DESCRIPTION
**Pull request by buffalojoec**
This PR decouples RPC-GraphQL's response type for "program accounts" queries from that of the return type of `getProgramAccounts`. This is an intentional and conscious design choice made in order to fully align query-ability and expected payloads with the types of the accounts schema.

TL/DR, I stuck `pubkey` inside the actual account payload itself as `address` because I think it makes more sense, especially considering the `Account` GraphQL interface already has this value.

### CODE REVIEW

**Comment by buffalojoec** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1793** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1793" target="_blank">Graphite</a> 
    * **PR #1794** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1794" target="_blank">Graphite</a> 
      * **PR #1795** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1795" target="_blank">Graphite</a> 
        * **PR #1796** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1796" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1796?utm_source=stack-comment).

**Review by mcintyre94 — APPROVED** [review]
LGTM! I guess this starts to move away a bit from the precise RPC response, but that makes sense as a design decision IMO since it probably wasn't written with graphQL in mind!

**Comment by buffalojoec** [comment]
> LGTM! I guess this starts to move away a bit from the precise RPC response, but that makes sense as a design decision IMO since it probably wasn't written with graphQL in mind!

This change in particular is me electing to serve another opinionated design choice (like defaulting to `jsonParsed`), and I think it's the right way to go for this API. I'm open to pushback on that.

On a related note, it might be possible, albeit annoying as hell, to add the type security at the same level as the new experimental Web3 JS. The only obstacle there is the fact that this thing just takes a damn string 😂

**Comment by buffalojoec** [comment]
### Merge activity

* **Oct 27, 6:20 PM**: @buffalojoec started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1796).

**Pull request merged**
