### PR TITLE
Parsing TransactionInstruction Data with New IInstruction Type

### PR DESCRIPTION
**Pull request by 0xCipherCoder**
Adds a `fromLegacyTransactionInstruction` function to convert the legacy shape to the modern one. 
 This pull request was created for https://app.gib.work/bounties/0a69df5e-4df3-497e-b180-2c5008e6dc18 in an attempt to solve a bounty #3593 . Payment for the bounty is immediately sent to the contributor after merge.

### CODE REVIEW

**Comment by 0xCipherCoder** [comment]
@steveluscher I tried to run the below command and got the output as attached in the screenshot. 

```bash
pnpm test:lint && pnpm test:typecheck && pnpm test:prettier
```

Screenshot 2024-11-21 173200


But there are few errors as well getting triggered - 

```sh
src/__tests__/instruction-test.ts:1:29 - error TS7016: Could not find a declaration file for module '@solana/instructions'. '/Cipher/OpenSource/solana-web3.js/packages/instructions/dist/index.node.cjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/solana__instructions` if it exists or add a new declaration (.d.ts) file containing `declare module '@solana/instructions';`

1 import { AccountRole } from '@solana/instructions';
                              ~~~~~~~~~~~~~~~~~~~~~~
```

Is this expected?

**Comment by steveluscher** [comment]
Generally, you have to run those _cross workspace_. Our cross-workspace task runner is called Turborepo.

```shell
pnpm turbo test:lint test:typecheck test:prettier
```

Running with `turbo` will ensure that your package is built/tested, but also that all of the packages that _it_ depends on are also built.

**Comment by 0xCipherCoder** [comment]
> Generally, you have to run those _cross workspace_. Our cross-workspace task runner is called Turborepo.
> 
> ```shell
> pnpm turbo test:lint test:typecheck test:prettier
> ```
> 
> Running with `turbo` will ensure that your package is built/tested, but also that all of the packages that _it_ depends on are also built.

Thanks! @steveluscher 
I tried with this command and initially worked fine with assertion#lint exited. But running again its exiting at different stages due to WSL setup on local. Is there any other way to test it?

```bash
@solana/errors#test:lint: command (/Cipher/OpenSource/solana-web3.js/packages/errors) /home/cipher/.nvm/versions/node/v21.7.1/bin/pnpm run test:lint exited (137)

 Tasks:    85 successful, 101 total
Cached:    85 cached, 101 total
  Time:    51.547s 
Failed:    @solana/errors#test:lint

 ERROR  run failed: command  exited (137)
```

**Comment by 0xCipherCoder** [comment]
@steveluscher This worked fine with the particular package compact where changes are present. Is this fine?


Screenshot 2024-11-22 051608


Screenshot 2024-11-22 051342

**Pull request closed without merging**
