### PR TITLE
Move address table lookup compile + codec into transaction-messages

### PR DESCRIPTION
**Pull request by mcintyre94**
This PR moves the logic to compile address lookup tables, and the associated codec, into transaction-messages

### CODE REVIEW

**Comment by mcintyre94** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2451?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2451** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2451?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2450** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2450?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @mcintyre94 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by lorisleiva — APPROVED** [review]
Nice! Thank you for renaming the "serializers" folder to "codecs".

**Comment by mcintyre94** [comment]
Very happy to leave serializers behind for codecs! 🚀

**Comment by mcintyre94** [comment]
### Merge activity

* **Apr 8, 6:06 AM EDT**: @mcintyre94 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2451).

**Pull request merged**
