### PR TITLE
docs(experimental): add custom retry logic example

### PR DESCRIPTION
**Pull request by quellen-sol**
Example shows a simple retrying transport that will retry up to `MAX_ATTEMPTS`. Would appreciate any feedback regarding implementation, as I wasn't too sure how much error handling would be best to show, for example.

Thanks! Super excited to start using this!

### CODE REVIEW

**Comment by steveluscher** [comment]
Cool; I like it!

What do you think about this: often when we talk about retry we talk about smearing those retries across time. If you try 4 times in a loop, you might get the same result every time because the conditions haven't changed. On the other hand if you introduce a _time_ delay between retries, you might have more success.

Want to try to introduce a concept like that, and then we'll get this in?

Reading: https://dzone.com/articles/understanding-retry-pattern-with-exponential-back

**Review by steveluscher — CHANGES_REQUESTED** [review]
Cool; I like it!

What do you think about this: often when we talk about retry we talk about smearing those retries across time. If you try 4 times in a loop, you might get the same result every time because the conditions haven't changed. On the other hand if you introduce a time delay between retries, you might have more success.

Want to try to introduce a concept like that, and then we'll get this in?

Reading: https://dzone.com/articles/understanding-retry-pattern-with-exponential-back

**Comment by quellen-sol** [comment]
Hah! I was debating whether or not to use exponential backoff in the example. I definitely agree it'd be nice to introduce that concept, will do, ty!

**Review by steveluscher — APPROVED** [review]
Looks good! Only thing that's not handled here that you would want for a production version is cancellation (eg. listening to the `abortSignal`) but it's good enough for an example.

**Pull request merged**
