### PR TITLE
add bank hash to frozen slot update

### PR DESCRIPTION
**Pull request by diman-io**
This is a corresponding PR to https://github.com/anza-xyz/agave/pull/3881

### CODE REVIEW

**Review by buffalojoec — COMMENTED** [review]
Lgtm, just have to make the linter happy. 😊

**Comment by diman-io** [comment]
@buffalojoec fixed

**Review by steveluscher — COMMENTED** [review]
This is still open on the `anza-xyz/agave` repo. Is it for sure going in?

**Comment by steveluscher** [comment]
The 2.x line has moved. Can you reopen this PR at https://github.com/anza-xyz/solana-web3.js so that you get credit for the change?

**Comment by diman-io** [comment]
@steveluscher just did it.
I saw your comment, but unfortunately, all I can do is keep reminding and hope that someone doesn’t miss the email and finds the time to hit the merge button.
In the next reminder, I’ll tag the community pr subscribers group to increase the chances…
Once, I waited for several months 😭 😂

**Pull request closed without merging**
