### PR TITLE
refactor(experimental): remove @solana/rpc-core and @solana/rpc-transport

### PR DESCRIPTION
**Pull request by lorisleiva**
Now that everything has been rewired, we can safely dispose of the `@solana/rpc-core` and `@solana/rpc-transport` packages.

RPC packages reshuffle@2x (15)

### CODE REVIEW

**Comment by lorisleiva** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2158?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#2158** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2158?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2157** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2157?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2156** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2156?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2155** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2155?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2154** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2154?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2153** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2153?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2152** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2152?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2151** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2151?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2150** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2150?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2149** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2149?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2148** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2148?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2147** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2147?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2146** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2146?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2145** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2145?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2144** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2144?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2158?utm_source=stack-comment).

**Review by steveluscher — COMMENTED** [review]
You wanted to remove this in this PR, right?

```ts
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Duplicated types will be removed in a follow-up PR once /rpc-core and /rpc-transports have been removed.
export * from '@solana/rpc-types';
```

**Comment by steveluscher** [comment]
There are a few mentions of `@solana/rpc-core` and `@solana/rpc-transports` in READMEs that need to be nerfed.

**Comment by lorisleiva** [comment]
> You wanted to remove this in this PR, right?

Yes, I just did! 🙂 

> There are a few mentions of @solana/rpc-core and @solana/rpc-transports in READMEs that need to be nerfed.

Yes, I need to update all the READMEs in follow up PRs but since we all seem to be working on RPC related stuff I wanted this stack to be mergeable asap.

**Review by buffalojoec — APPROVED** [review]
How good did this feel to commit?

stamp

**Comment by lorisleiva** [comment]
✅ This PR was merged as part of https://github.com/solana-labs/solana-web3.js/pull/2168.

**Pull request closed without merging**
