### PR TITLE
test: fix tests forward for 1.16.x

### PR DESCRIPTION
**Pull request by steveluscher**
# Summary

1.16 added a `space` param to gPA and changed an error message. This PR updates the web3.js tests to handle that, and a whole lot more fiddling with object shapes and strictness.

# NOTE

The _really_ bad thing about this is that when the tests break, you get this inscrutable error from Jest:

```
FAIL   Unit Test (Node)  src/rpc-methods/__tests__/get-multiple-accounts-test.ts
  ● Test suite failed to run

    DataCloneError: Symbol(jest.asymmetricMatcher) could not be cloned.

      at reportSuccess (../../node_modules/.pnpm/jest-worker@29.7.0/node_modules/jest-worker/build/workers/threadChild.js:98:34)
```

I think this is because of the presence of `BigInts` and Jest's inability to…

```
TypeError: Do not know how to serialize a BigInt
```

I haven't filed a bug with Jest yet, but the workaround I have is to:

* Convert all of the `toStrictMatch()` to `toMatchObject()`
* Re-run the tests and figure out what broke
* Undo undo undo to put them all back
* Fix the problem

# Test Plan

```
pnpm turbo test:unit:browser
pnpm turbo test:unit:node
```

### CODE REVIEW

**Comment by steveluscher** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1655** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1655" target="_blank">Graphite</a>  👈
    * **PR #1640** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1640" target="_blank">Graphite</a> 
      * **PR #1641** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1641" target="_blank">Graphite</a> 
        * **PR #1622** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1622" target="_blank">Graphite</a> 
          * **PR #1623** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1623" target="_blank">Graphite</a> 
            * **PR #1626** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1626" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1655?utm_source=stack-comment).

**Review by buffalojoec — CHANGES_REQUESTED** [review]
I think you forgot `getAccountInfo`.

Heads up they call it `size` in this one, not `space`.
https://docs.solana.com/api/http#getaccountinfo

**Comment by steveluscher** [comment]
Oh, hunh. All the tests passed, so I stopped. Looking…

**Comment by steveluscher** [comment]
Oh dear. Those other tests didn't use `expect.objectContaining` so they weren't exhaustive checks.

**Comment by buffalojoec** [comment]
> Oh dear. Those other tests didn't use `expect.objectContaining` so they weren't exhaustive checks.

This is what I was afraid of

**Comment by steveluscher** [comment]
Uh, no really. How do you combine `toStrictEqual` with inner `expect.any(...)`.

**Comment by buffalojoec** [comment]
> Uh, no really. How do you combine `toStrictEqual` with inner `expect.any(...)`.

You just put the value instead of expect right? Or are you saying for the whole object?

**Comment by steveluscher** [comment]
There's a bug in Jest. I'm working through it. Will have a PR in a bit.

**Comment by steveluscher** [comment]
Crap. Missed the legacy test runner.

**Comment by steveluscher** [comment]
K, the tests passed at long last. I'm going to slam this in so that we can see a few more test runs over time.

**Comment by buffalojoec** [comment]
> K, the tests passed at long last. I'm going to slam this in so that we can see a few more test runs over time.

not looking

**Pull request merged**
