### PR TITLE
chore: Fixed sendTransactionError types

### PR DESCRIPTION
**Pull request by Woody4618**
Reverted TransactionError types and added transactionMessage and logs directly into the SendTransactionError

### CODE REVIEW

**Comment by joncinque** [comment]
Was this meant to be a breaking change? There's some code in the account compression depending on the `logs` parameter as it used to be: https://github.com/solana-labs/solana-program-library/blob/b9d8fff34afe7ae852e13bae9063dd95f1af6501/account-compression/sdk/tests/utils.ts#L40

I'm happy to make the change on the library side, but I want to make sure this breakage won't cause other downstream issues.

**Comment by steveluscher** [comment]
cc/ @Woody4618

**Comment by Woody4618** [comment]
Hey, i can probably just fix that by renaming the type back to logs right?

**Comment by steveluscher** [comment]
`git pull --rebase` your working copy and `pnpm i`; there was a problem with `rpc-websockets` that was fixed the same day too.

**Comment by steveluscher** [comment]
I would probably satisfy backward compat by adding a getter for `logs` and deprecating it.
```ts
class SendTransactionError {
    /* @deprecated Use `await getLogs()` instead
    get logs() {
        return this.transactionError.logs;
    }
}
```

**Comment by Woody4618** [comment]
I renamed it here: https://github.com/solana-labs/solana-web3.js/pull/2769 

Is that also okey?

**Pull request merged**
