### PR TITLE
refactor(experimental): refactor the default subscriptions transport with `pipe` to make it more readable

### PR DESCRIPTION
**Pull request by steveluscher**
# Summary

Much nicer to read these linearly rather than inside-out.

# Test Plan

CI run

### CODE REVIEW

**Comment by steveluscher** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1624** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1624" target="_blank">Graphite</a>  👈
    * **PR #1625** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1625" target="_blank">Graphite</a> 
      * **PR #1622** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1622" target="_blank">Graphite</a> 
        * **PR #1623** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1623" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1624?utm_source=stack-comment).

**Review by buffalojoec — APPROVED** [review]
Nice!!! Looks much cleaner

**Comment by steveluscher** [comment]
Thanks to you!

**Comment by steveluscher** [comment]
### Merge Activity

* **Sep 25, 3:12 PM**: @steveluscher started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1624).

**Pull request merged**
