### PR TITLE
chore: sort all type constituents

### PR DESCRIPTION
**Pull request by steveluscher**
# Summary

Our linter didn't sort type constituents before – only object keys. This PR introduces the same A-Z sorting for types.

# Test Plan

- CI run
- run `pnpm style:fix` over and over until no more changes

### CODE REVIEW

**Comment by steveluscher** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2272?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2272** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2272?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2271** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2271?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @steveluscher and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by buffalojoec — APPROVED** [review]
shocked reading

**Comment by buffalojoec** [comment]
This is pretty extreme, but I'm not against it.

**Comment by steveluscher** [comment]
### Merge activity

* **Mar 6, 5:57 PM PST**: @steveluscher started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2272).

**Pull request merged**
