### PR TITLE
Accept bigints in RPC error factories

### PR DESCRIPTION
**Pull request by lorisleiva**
This PR makes the failing tests introduced in the previous PR pass.

See https://github.com/solana-labs/solana-web3.js/pull/3518.

### CODE REVIEW

**Comment by lorisleiva** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3519?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3519** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3519?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#3518** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lorisleiva and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by mcintyre94 — APPROVED** [review]
Nice, looks good!

**Review by steveluscher — APPROVED** [review]
I'm fine with this, but I don't think I actually understand why the numeric keypath allowlist is insufficient for this. The root data has that special case in the transport (which we could add to the subscriptions one) and for the errors-as-data (ie. instruction errors) I think we could put a keypath here:

https://github.com/solana-labs/solana-web3.js/blob/d83eaaf66958345d0eb28ec35e309b27a3e6e0ab/packages/rpc-api/src/index.ts#L287-L290

Anyway, I think that what this is doing is playing fast and loose with the types, but only internal to the transport; devs will never see a bigint error code.

Added via Giphy

**Comment by lorisleiva** [comment]
### Merge activity

* **Nov 5, 3:30 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3519).

**Pull request merged**
