### PR TITLE
refactor(experimental): errors: `codecs-numbers` package

### PR DESCRIPTION
**Pull request by buffalojoec**
Adds custom `SolanaError` throws to the `@solana/codecs-numbers` package.

### CODE REVIEW

**Comment by buffalojoec** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2191?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* **#2192** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2192?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2191** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2191?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2190** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2190?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2189** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2189?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2188** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2188?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2187** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2187?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2186** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2186?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2185** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2185?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2184** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2184?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2182** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2182?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2183](https://github.com/solana-labs/solana-web3.js/pull/2183) <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2183?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2191?utm_source=stack-comment).

**Review by steveluscher — CHANGES_REQUESTED** [review]
Added via Giphy

**Review by steveluscher — APPROVED** [review]
Added via Giphy

**Comment by steveluscher** [comment]
### Merge activity

* **Feb 29, 11:33 AM PST**: @steveluscher started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2191).

**Pull request merged**
