### PR TITLE
Remove temporary fix for Agave issue 479

### PR DESCRIPTION
**Pull request by lorisleiva**
This PR removes the temporary request transformer that was waiting for [this PR](https://github.com/anza-xyz/agave/pull/483) to be merged and available on mainnet-beta.

### CODE REVIEW

**Comment by lorisleiva** [comment]
* **#3184** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3184?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lorisleiva and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by mcintyre94 — APPROVED** [review]
Nice!

**Review by steveluscher — APPROVED** [review]
Added via Giphy

**Comment by lorisleiva** [comment]
### Merge activity

* **Sep 10, 3:48 AM EDT**: @lorisleiva started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3184).

**Pull request merged**
