### PR TITLE
refactor(experimental): add getHealth API method

### PR DESCRIPTION
**Pull request by amilz**
I needed `getHealth` the other day and went down a rabbit hole.

Adds the `getHealth` method to the `rpc-core` package, providing a way to check the health status of a Solana node. The method returns "ok" if the node is healthy.

A corresponding test has also been included in the `rpc-methods/__tests__` directory to ensure that both healthy and unhealthy node statuses are handled correctly.

Related issue: https://github.com/solana-labs/solana-web3.js/issues/1449

### CODE REVIEW

**Review by buffalojoec — APPROVED** [review]
Nice, thanks!!

**Comment by steveluscher** [comment]
Are you building with `experimental` @amilz?! Awesome! Keep the feedback coming.

**Comment by amilz** [comment]
Ya 🙌 @steveluscher I am experimenting with it...nothing major yet. Where's the best place to provide feedback?

**Comment by buffalojoec** [comment]
> Ya 🙌 @steveluscher I am experimenting with it...nothing major yet. Where's the best place to provide feedback?

Issues or comments on GitHub are super useful. You can always check out the [roadmap issues](https://github.com/solana-labs/solana-web3.js/issues/1469) too!

**Pull request merged**
