### PR TITLE
chore: fast forward to slot 32 when starting a test validator

### PR DESCRIPTION
**Pull request by steveluscher**
chore: fast forward to slot 32 when starting a test validator

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/solana-labs/solana-web3.js/pull/1424).
* #1422
* #1421
* __->__ #1424
* #1420
* #1419
* #1416
* #1415
* #1414
* #1413
* #1412
* #1400

### CODE REVIEW

**Comment by steveluscher** [comment]
This makes any tests that assert on `finalized` commitment work immediately after the validator starts up.

**Review by joncinque — APPROVED** [review]
Woo!

**Comment by steveluscher** [comment]
```
16) Connection
     get confirmed block
       gets a block having a parent:
   SolanaJSONRPCError: failed to get confirmed block: Slot 1 was skipped, or missing due to ledger jump to recent snapshot
    at Connection.getConfirmedBlock (src/connection.ts:5127:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Context.<anonymous> (test/connection.test.ts:4095:32)
```
giphy

**Comment by steveluscher** [comment]
I swear if I have to start two different validator instances just to run the legacy web3.js tests…

**Comment by steveluscher** [comment]
I give up. No testing with `finalized` until I have a brainwave here.

**Pull request closed without merging**
