### PR TITLE
feat: add createProgramAddress

### PR DESCRIPTION
**Pull request by jackcmay**
Add function to derive Program Addresses

fixes: #909

### CODE REVIEW

**Comment by jackcmay** [comment]
@CriesofCarrots Any feedback from a .js programmer's perspective?

**Comment by mvines** [comment]
lgtm, I was surprised to see the `Promise`, but I guess `sha256()` spawns a native thread to hash?

**Comment by CriesofCarrots** [comment]
lgtm too. Yeah, `crypto-hash` uses worker_threads

**Pull request merged**
