### PR TITLE
Enforce that `publicKeyBytes` is a length-32 array

### PR DESCRIPTION
**Pull request by nishadsingh1**

### CODE REVIEW

**Comment by mvines** [comment]
Hey this needs to be moved to https://github.com/solana-labs/solana

**Comment by jackcmay** [comment]
@nishadsingh1 I'll move it to the Solana repo and follow through to commit it.  Thanks for finding the issue and such a quick fix!  Do you happen to have the test case that led you to find the issue handy?

**Comment by nishadsingh1** [comment]
Yep!

```
let programId = new PublicKey('4ckmDgGdxQoPDLUkDT3vHgSAkzA3QRdNq5ywwY4sUSJn');
let {sha256} = require('crypto-hash')
let seeds = [ new PublicKey('H4snTKK9adiU15gP22ErfZYtro3aqR9BTMXiH3AwiUTQ').toBuffer(), new BN(2).toArrayLike(Buffer, 'le', 8)];
PublicKey.createProgramAddress(seeds, programId);
```

**Comment by nishadsingh1** [comment]
For future reference: do all updates go to https://github.com/solana-labs/solana?

**Comment by mvines** [comment]
> For future reference: do all updates go to https://github.com/solana-labs/solana?

Yeah.  This repo exists only for releasing to npmjs at this point.  On the list to clean up but low pri

**Comment by jackcmay** [comment]
Moved to the solana repo: https://github.com/solana-labs/solana/pull/11951

**Pull request closed without merging**
