### PR TITLE
Support SPL Token account state within the schema for Token Account 

### PR DESCRIPTION
**Pull request by Hrushi20**
## Support for following: 

- TransferFeeAmount
- ImmutableOwner
- MemoTransfer
- CpiGuard
- NonTransferableAccount
- ConfidentialTransferFeeAmount
- TransferHookAccount

Ref https://github.com/solana-labs/solana-web3.js/issues/2644.

### CODE REVIEW

**Comment by Hrushi20** [comment]
Hey, I thought the changes are pretty small and hence merged all accounts into a single PR. Hope that's fine :)

**Comment by buffalojoec** [comment]
> Hey, I thought the changes are pretty small and hence merged all accounts into a single PR. Hope that's fine :)

Yeah! Not a problem. In that case, do you mind adding the last one, `confidentialTransferAccount`?

**Comment by Hrushi20** [comment]
I created a separate PR #2699 for that. Thanks.

**Comment by buffalojoec** [comment]
> I created a separate PR #2699 for that. Thanks.

Sounds good, you'll just have to rebase this one then.

**Review by buffalojoec — APPROVED** [review]
And that does it for account state!! Thanks!

**Pull request merged**
