### PR TITLE
Update dependencies: mitigate potential security issues

### PR DESCRIPTION
**Pull request by paulmillr**
Is this repo open source? Why are the issues closed? There are zero points to where to report issues, or where to discuss them. Does not seem "open" to me. 

In any case, your cryptography dependencies are old and can break easily — I suggest to upgrade to new ones. I can prepare the PR.

### CODE REVIEW

**Comment by CriesofCarrots** [comment]
This repository is a mirror of https://github.com/solana-labs/solana/tree/master/web3.js
Please direct any issues or PRs there, thanks!

**Comment by stephenplusplus** [comment]
+1 to including a note in the README about the upstream repository for reporting issues.

**Comment by steveluscher** [comment]
Done, @stephenplusplus. https://github.com/solana-labs/solana/commit/00ce8057881cff4181fb3d414a03fcd90b3be1ea

**Comment by steveluscher** [comment]
I literally don't even have admin rights to close this PR. @joeaba, can you add me?

**Comment by joeaba** [comment]
Sure thing

**Comment by stephenplusplus** [comment]
Thanks @steveluscher!

**Pull request closed without merging**
