### PR TITLE
custom css theme

### PR DESCRIPTION
**Pull request by manuel-calavera**
custom css theme implemented for web3 js doc to support common style among all Solana docs

### CODE REVIEW

**Comment by mvines** [comment]
looks good to me!  Is this ready to merge or is still a work in progress?

**Comment by manuel-calavera** [comment]
@mvines ready to merge. let me know if you hv any comments or suggestions.

**Comment by mvines** [comment]
@manuel-calavera hey there's some white text with this new style: that is problematic, here are some examples:
1. https://solana-labs.github.io/solana-web3.js/file/src/layout.js.html#lineNumber8 -- the identifiers are the white, same as the background, making the source unreadable
2. https://solana-labs.github.io/solana-web3.js/function/index.html#static-function-publicKey -- the "publicKey" identifier in `import {publicKey} from '@solana/web3'` is very difficult to read

**Pull request merged**
