### PR TITLE
refactor(experimental): a function you can use to get a transaction's signature

### PR DESCRIPTION
**Pull request by steveluscher**
# Summary

The signature of the fee payer is by definition the signature of the transaction. This is a helper that makes you not have to think about that fact.

# Test Plan

```
cd packages/transactions
pnpm test:unit:browser
pnpm test:unit:node
```

### CODE REVIEW

**Comment by steveluscher** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1643** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1643" target="_blank">Graphite</a> 
    * **PR #1644** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1644" target="_blank">Graphite</a> 
      * **PR #1645** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1645" target="_blank">Graphite</a> 
        * **PR #1646** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1646" target="_blank">Graphite</a> 
          * **PR #1647** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1647" target="_blank">Graphite</a> 
            * **PR #1648** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1648" target="_blank">Graphite</a> 
              * **PR #1649** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1649" target="_blank">Graphite</a> 
                * **PR #1650** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1650" target="_blank">Graphite</a> 
                  * **PR #1651** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1651" target="_blank">Graphite</a> 
                    * **PR #1684** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1684" target="_blank">Graphite</a> 
                      * **PR #1685** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1685" target="_blank">Graphite</a>  👈
                        * **PR #1686** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1686" target="_blank">Graphite</a> 
                          * **PR #1687** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1687" target="_blank">Graphite</a> 
                    * **PR #1678** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1678" target="_blank">Graphite</a> 
                    * **PR #1652** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1652" target="_blank">Graphite</a> 
                      * **PR #1653** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1653" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1685?utm_source=stack-comment).

**Comment by steveluscher** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1643** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1643" target="_blank">Graphite</a> 
    * **PR #1644** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1644" target="_blank">Graphite</a> 
      * **PR #1645** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1645" target="_blank">Graphite</a> 
        * **PR #1646** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1646" target="_blank">Graphite</a> 
          * **PR #1647** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1647" target="_blank">Graphite</a> 
            * **PR #1648** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1648" target="_blank">Graphite</a> 
              * **PR #1649** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1649" target="_blank">Graphite</a> 
                * **PR #1650** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1650" target="_blank">Graphite</a> 
                  * **PR #1651** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1651" target="_blank">Graphite</a> 
                    * **PR #1684** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1684" target="_blank">Graphite</a> 
                      * **PR #1685** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1685" target="_blank">Graphite</a>  👈
                        * **PR #1686** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1686" target="_blank">Graphite</a> 
                          * **PR #1687** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1687" target="_blank">Graphite</a> 
                    * **PR #1678** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1678" target="_blank">Graphite</a> 
                    * **PR #1652** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1652" target="_blank">Graphite</a> 
                      * **PR #1653** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1653" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1685?utm_source=stack-comment).

**Comment by steveluscher** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1643** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1643" target="_blank">Graphite</a> 
    * **PR #1644** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1644" target="_blank">Graphite</a> 
      * **PR #1645** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1645" target="_blank">Graphite</a> 
        * **PR #1646** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1646" target="_blank">Graphite</a> 
          * **PR #1647** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1647" target="_blank">Graphite</a> 
            * **PR #1648** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1648" target="_blank">Graphite</a> 
              * **PR #1649** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1649" target="_blank">Graphite</a> 
                * **PR #1650** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1650" target="_blank">Graphite</a> 
                  * **PR #1651** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1651" target="_blank">Graphite</a> 
                    * **PR #1684** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1684" target="_blank">Graphite</a> 
                      * **PR #1685** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1685" target="_blank">Graphite</a>  👈
                        * **PR #1686** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1686" target="_blank">Graphite</a> 
                          * **PR #1687** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1687" target="_blank">Graphite</a> 
                    * **PR #1678** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1678" target="_blank">Graphite</a> 
                    * **PR #1652** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1652" target="_blank">Graphite</a> 
                      * **PR #1653** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1653" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1685?utm_source=stack-comment).

**Comment by steveluscher** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1643** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1643" target="_blank">Graphite</a> 
    * **PR #1644** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1644" target="_blank">Graphite</a> 
      * **PR #1645** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1645" target="_blank">Graphite</a> 
        * **PR #1646** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1646" target="_blank">Graphite</a> 
          * **PR #1647** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1647" target="_blank">Graphite</a> 
            * **PR #1648** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1648" target="_blank">Graphite</a> 
              * **PR #1649** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1649" target="_blank">Graphite</a> 
                * **PR #1650** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1650" target="_blank">Graphite</a> 
                  * **PR #1651** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1651" target="_blank">Graphite</a> 
                    * **PR #1684** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1684" target="_blank">Graphite</a> 
                      * **PR #1685** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1685" target="_blank">Graphite</a>  👈
                        * **PR #1686** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1686" target="_blank">Graphite</a> 
                          * **PR #1687** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1687" target="_blank">Graphite</a> 
                    * **PR #1678** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1678" target="_blank">Graphite</a> 
                    * **PR #1652** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1652" target="_blank">Graphite</a> 
                      * **PR #1653** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1653" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1685?utm_source=stack-comment).

**Comment by steveluscher** [comment]
### Merge Activity

* **Oct 7, 12:15 AM**: @steveluscher started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1685).

**Review by buffalojoec — COMMENTED** [review]
\* insert good signature gif here

**Pull request merged**
