### PR TITLE
Let the new coded exceptions from `codecs-core` bubble up as-is through `@solana/options` et al

### PR DESCRIPTION
**Pull request by steveluscher**
# Summary

The developer will receive a `SOLANA_ERROR__CODECS_EXPECTED_FIXED_LENGTH_GOT_VARIABLE_LENGTH` and should be able to determine which thing was of the wrong type based on the line that threw that error. I don't think we need to rethrow/respecify the error here.

### CODE REVIEW

**Comment by steveluscher** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2244?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2244** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2244?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2243** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2243?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2242** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2242?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @steveluscher and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by buffalojoec — APPROVED** [review]
Nice. I'll also need to add this in some of `codecs-core`, where the assertion error should also bubble up like so.

https://github.com/solana-labs/solana-web3.js/pull/2189/files#diff-5ce092ba320e681ef239979138cbb980d1002062e78222acd522c98fab1fe2bdR24-R31

**Review by lorisleiva — APPROVED** [review]
Agreed. Also, TypeScript should prevent these errors so, unless you're DHH, it's unlikely to affect users.

**Comment by steveluscher** [comment]
>  I'll also need to add this in some of codecs-core, where the assertion error should also bubble up like so.

Done, in this PR!

**Comment by steveluscher** [comment]
### Merge activity

* **Mar 4, 12:41 PM PST**: @steveluscher started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2244).

**Pull request merged**
