### PR TITLE
Show no Turbo logs except when there is an error

### PR DESCRIPTION
**Pull request by steveluscher**
# Summary

So many logs.

How would you folks feel about Turborepo showing _nothing_ unless there's an error?

```
• Packages in scope: @solana/accounts, @solana/addresses, @solana/assertions, @solana/build-scripts, @solana/codecs, @solana/codecs-core, @solana/codecs-data-structures, @solana/codecs-numbers, @solana/codecs-strings, @solana/compat, @solana/crypto-impl, @solana/errors, @solana/functional, @solana/instructions, @solana/keys, @solana/options, @solana/programs, @solana/rpc, @solana/rpc-api, @solana/rpc-graphql, @solana/rpc-parsed-types, @solana/rpc-spec, @solana/rpc-spec-types, @solana/rpc-subscriptions, @solana/rpc-subscriptions-api, @solana/rpc-subscriptions-spec, @solana/rpc-subscriptions-transport-websocket, @solana/rpc-transformers, @solana/rpc-transport-http, @solana/rpc-types, @solana/signers, @solana/sysvars, @solana/test-config, @solana/test-matchers, @solana/text-encoding-impl, @solana/transaction-confirmation, @solana/transactions, @solana/tsconfig, @solana/web3.js, @solana/web3.js-experimental, @solana/web3.js-legacy-sham, @solana/webcrypto-ed25519-polyfill, @solana/ws-impl
• Running test:lint in 43 packages
• Remote caching enabled
@solana/accounts:test:lint: cache miss, executing 9db95c74ecbf331c
@solana/accounts:test:lint:
@solana/accounts:test:lint: > @solana/accounts@2.0.0-preview.2 test:lint /home/sol/src/solana-web3.js-git/packages/accounts
@solana/accounts:test:lint: > jest -c ../../node_modules/@solana/test-config/jest-lint.config.ts --rootDir . --silent
@solana/accounts:test:lint:
                             PASS   ESLint  src/rpc-api/common.ts
@solana/accounts:test:lint:  PASS   ESLint  src/types/global.d.ts
@solana/accounts:test:lint:  PASS   ESLint  src/index.ts
@solana/accounts:test:lint:  PASS   ESLint  src/maybe-account.ts
@solana/accounts:test:lint:  PASS   ESLint  src/parse-account.ts
@solana/accounts:test:lint:  PASS   ESLint  src/account.ts
@solana/accounts:test:lint:  FAIL   ESLint  src/decode-account.ts
@solana/accounts:test:lint:
@solana/accounts:test:lint: /home/sol/src/solana-web3.js-git/packages/accounts/src/decode-account.tsa/accounts:test:lint:
@solana/accounts:test:lint:   68:9  error  Unexpected constant condition  no-constant-conditionsolana/accounts:test:lint:
@solana/accounts:test:lint:
@solana/accounts:test:lint: ✖ 1 problem (1 error, 0 warnings)
@solana/accounts:test:lint:
@solana/accounts:test:lint:  PASS   ESLint  src/__typetests__/maybe-account-typetest.ts
@solana/accounts:test:lint:  PASS   ESLint  src/rpc-api/getAccountInfo.ts
@solana/accounts:test:lint:  PASS   ESLint  src/__tests__/decode-account-test.ts
@solana/accounts:test:lint:  PASS   ESLint  src/__typetests__/fetch-account-typetest.ts
@solana/accounts:test:lint:  PASS   ESLint  src/__tests__/parse-account-test.ts
@solana/accounts:test:lint:  PASS   ESLint  src/__typetests__/decode-account-typetest.ts
@solana/accounts:test:lint:  PASS   ESLint  src/__tests__/fetch-account-test.ts
@solana/accounts:test:lint:  PASS   ESLint  src/__typetests__/parse-account-typetest.ts
@solana/accounts:test:lint:  PASS   ESLint  src/rpc-api/index.ts
@solana/accounts:test:lint:  PASS   ESLint  src/__tests__/maybe-account-test.ts
@solana/accounts:test:lint:  PASS   ESLint  src/__tests__/__setup__.ts
@solana/accounts:test:lint:  PASS   ESLint  src/rpc-api/getMultipleAccounts.ts
@solana/accounts:test:lint:  PASS   ESLint  src/fetch-account.ts

@solana/accounts:test:lint: Test Suites: 1 failed, 19 passed, 20 total
@solana/accounts:test:lint: Tests:       1 failed, 19 passed, 20 total
@solana/accounts:test:lint: Snapshots:   0 total
@solana/accounts:test:lint: Time:        1.519 s, estimated 2 s
@solana/accounts:test:lint:  ELIFECYCLE  Command failed with exit code 1.
@solana/accounts:test:lint: ERROR: command finished with error: command (/home/sol/src/solana-web3.js-git/packages/accounts) /home/sol/.local/share/pnpm/pnpm run test:lint exited (1)
@solana/accounts#test:lint: command (/home/sol/src/solana-web3.js-git/packages/accounts) /home/sol/.local/share/pnpm/pnpm run test:lint exited (1)
@solana/accounts:test:lint:
 Tasks:    38 successful, 39 total
Cached:    38 cached, 39 total
  Time:    11.009s st:lint:
Failed:    @solana/accounts#test:lint
@solana/accounts:test:lint:
 ERROR  run failed: command  exited (1)
```

Related discussion: https://github.com/vercel/turbo/issues/4042

### CODE REVIEW

**Comment by steveluscher** [comment]
* **#2366** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2366?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @steveluscher and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by buffalojoec — COMMENTED** [review]
Ehhh, personally I love the colors, but this could be helpful. I defer to the rest of the group.

**Review by steveluscher — COMMENTED** [review]
Yeah, I could totally just do `--output-logs errors-only` for myself locally.

**Review by lorisleiva — APPROVED** [review]
I like it but I don't have a strong opinion on it if others don't.

**Comment by steveluscher** [comment]
I'll land this; you can reverse it with `--output-logs full` or `--output-logs new-only`.

**Pull request merged**
