### PR TITLE
refactor(experimental): add addCodecSentinel to @solana/codecs-core

### PR DESCRIPTION
**Pull request by lorisleiva**
This PR adds a new `addCodecSentinel` primitive.

The `addCodecSentinel` function provides a new way of delimiting the size of a codec. It allows us to add a sentinel to the end of the encoded data and to read until that sentinel is found when decoding. It accepts any codec and a `Uint8Array` sentinel responsible for delimiting the encoded data.

```ts
const codec = addCodecSentinel(getUtf8Codec(), new Uint8Array([255, 255]));
codec.encode('hello');
// 0x68656c6c6fffff
//   |        └-- Our sentinel.
//   └-- Our encoded string.
```

### CODE REVIEW

**Comment by lorisleiva** [comment]
* **#2419** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2419?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lorisleiva and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by buffalojoec — APPROVED** [review]
Nice! How might one chain sentinel codecs together?

Also, how come this is named in reverse order of the other codecs, like `ArrayCodec` and `MapCodec`. Here it's reversed (`CodecSentinel`). Assuming because of the nature of the sentinel coming after the codec bit? Since this still produces a valid codec, it did throw me off a bit.

**Comment by lorisleiva** [comment]
Hey @buffalojoec,

### Regarding chaining sentinels

You can just use any other codec to chain them such as `getStructCodec` of `getTupleCodec`.


```ts
const sentinel = new Uint8Array([255]);
const person = getStructCodec([
    ['firstname', addCodecSentinel(getUtf8Codec(), sentinel)],
    ['lastname', addCodecSentinel(getUtf8Codec(), sentinel)],
    ['age', getU8Codec()],
]);

person.encode({ age: 42, firstname: 'John', lastname: 'Doe' });
// 0x4a6f686eff446f65ff2a
//   |         |       └-- Age.
//   |         └-- Lastname.
//   └-- Firstname.
```

I added a couple of tests to illustrate that.


### Regarding codec naming conventions

There is a difference between primitive functions like `addCodecSentinel` and other type codecs such as `getArrayCodec`. Let me explain in a bit more detail.

Whilst all codec functions start with a verb, there are two categories of codec functions: the **codec primitives** and the **codec type helpers**.

#### Codec primitives

These functions are lower-level helper and live under the `@solana/codecs-core` package. They allow us to **manipulate codecs** without worrying about their concrete types. For instance, the `fixCodecSize` primitive transforms a `VariableSizeCodec<T>` into a `FixedSizeCodec<T>` regardless of what `T` might be.

The naming convention for codec primitives is to describe that codec manipulation by starting with a verb. For instance:
- `mapCodec` (soon to be `transformCodec`) _maps_ (or _transforms_) a `Codec<T>` into a `Codec<U>` by accepting `T => U` and `U => T` functions.
- `reverseCodec` _reverses_ the bytes of a codec.
- `offsetCodec` _offsets_ the reading and writing cursors of a given codec.
- `fixCodecSize` _fixes_ the size of a codec by accepting a byte length.
- `addCodecSizePrefix` _adds_ a size prefix to the provided codec.
- `addCodecSentinel` _adds_ a sentinel at the end of the provided codec to identify its end.
- etc.

#### Codec type helpers

On the other hand, codec type helpers are meant to **provide codecs for specific types** and live under the other codec packages such as `@solana/codecs-numbers`, `@solana/codecs-strings`, etc. For instance `getU32Codec` will provide a `Codec<number>` and `getBase58Codec` will provide a `Codec<string>`. These can then be composed with codec primitives to create more complex serialisation strategies.

The naming convention for codec type helpers is `"get" + Type + "Codec"`. For instance:
- `getU16Codec` _gets_ a number codec using 2 bytes.
- `getBase58Codec` _gets_ a base58 encoded string codec.
- `getArrayCodec` _gets_ an `Array<T>` codec from a given `Codec<T>`.
- `getStructCodec` _gets_ an object codec from provided field codecs.
- etc.

Now, with this in mind, does `addCodecSentinel` still feel out of place?

**Comment by buffalojoec** [comment]
> Now, with this in mind, does `addCodecSentinel` still feel out of place?

Sorry, just circling back to this. Yeah, I think with that provided context this does seem like a proper name. Maybe it's because I didn't know about `addCodecSizePrefix` that I was a bit confused when I saw `add + Codec + T`? Either way, thanks for the insight into the patterns. Ship it!

**Review by mcintyre94 — APPROVED** [review]
LGTM!

**Comment by lorisleiva** [comment]
### Merge activity

* **Apr 4, 12:47 PM EDT**: @lorisleiva started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2419).

**Pull request merged**
