### PR TITLE
refactor(experimental): add constants to web3.js sham

### PR DESCRIPTION
**Pull request by steveluscher**
Addresses #1825.

### CODE REVIEW

**Comment by steveluscher** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1860** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1860?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1861** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1861?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1862** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1862?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
        * **PR #1863** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1863?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #1864** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1864?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1862?utm_source=stack-comment).

**Review by lorisleiva — APPROVED** [review]

**Review by mcintyre94 — APPROVED** [review]

**Review by buffalojoec — APPROVED** [review]
Lgtm, but I think I'm going to take this opportunity to cast my vote for adding `LAMPORTS_PER_SOL` to the new library.

People are going to be quite irked if that's gone.

**Comment by steveluscher** [comment]
It's not going to be that useful. The second that someone tries to do division they'll discover that you can't do division with `bigint`.

It might be more useful to create a bunch of math helpers (also OMG I'd rather leave that up to others so that they carefully think about how and when they round).

**Comment by steveluscher** [comment]
### Merge activity

* **Nov 20, 1:52 PM**: @steveluscher started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/1862).

**Pull request merged**
