### PR TITLE
refactor(experimental): errors: `codecs-data-structures` package

### PR DESCRIPTION
**Pull request by buffalojoec**
Adds custom `SolanaError` throws to the `@solana/codecs-data-structures`
package.

### CODE REVIEW

**Review by lorisleiva — CHANGES_REQUESTED** [review]
Same comment as previous PRs. These need to be broken down such that each error code tackles a specific scenario. I think we should prefix these errors with codecs so they are grouped together and easier to autocomplete. Like: `SOLANA_ERROR__CODECS_EXPECTED_FIXED_SIZE`

**Comment by buffalojoec** [comment]
> Same comment as previous PRs. These need to be broken down such that each error code tackles a specific scenario. I think we should prefix these errors with codecs so they are grouped together and easier to autocomplete. Like: `SOLANA_ERROR__CODECS_EXPECTED_FIXED_SIZE`

Sounds good. I wasn't sure how granular to get.

**Review by steveluscher — APPROVED** [review]
Added via Giphy

**Comment by steveluscher** [comment]
### Merge activity

* **Feb 29, 11:33 AM PST**: @steveluscher started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/2190).

**Pull request merged**
