### PR TITLE
Parsing TransactionInstruction Data with New IInstruction Type

### PR DESCRIPTION
**Pull request by shubhiscoding**
adds a fromLegacyTransactionInstruction function to convert the legacy shape to the modern one.. 
 This pull request was created for https://app.gib.work/bounties/0a69df5e-4df3-497e-b180-2c5008e6dc18 in an attempt to solve a bounty solana-labs/web3.js-issue-conveyer#8 . Payment for the bounty is immediately sent to the contributor after merge.

### CODE REVIEW

**Comment by shubhiscoding** [comment]
@steveluscher 
I want to apologize for the earlier state of the code—it was rushed, but I realize now I should have taken more time to polish it. have made few changes and tests also passed.
Whenever you have a moment, I'd greatly appreciate your review. Let me know if there's any other changes needed.

**Comment by shubhiscoding** [comment]
Hii @steveluscher Do I need to make any changes for this to be merged?

**Comment by shubhiscoding** [comment]
hii @steveluscher please review this! or it will go stale again..

**Comment by steveluscher** [comment]
The 2.x line has moved. Can you reopen this PR at https://github.com/anza-xyz/solana-web3.js so that you get credit for the change? I promise to review it next week if you do.

**Comment by shubhiscoding** [comment]
raised PR https://github.com/anza-xyz/solana-web3.js/pull/37

**Pull request closed without merging**
