### PR TITLE
refactor(experimental): changeset for unix timestamp bigint changes

### PR DESCRIPTION
**Pull request by buffalojoec**
I have no idea if this changeset makes sense with the release candidate, but I felt like this was at least a minor (breaking) change.

### CODE REVIEW

**Comment by buffalojoec** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3134?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3134** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3134?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#3130** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3130?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3122** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3122?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3129** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3129?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3121** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3121?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3120** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3120?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @buffalojoec and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by buffalojoec** [comment]
> I _think_ because we are in RC, `patch` is what we need as it'll bump `rc.1` to `rc.2` which is a breaking change anyway.

Alrighty, I've changed to `patch`!

**Review by steveluscher — APPROVED** [review]
Added via Giphy

**Comment by buffalojoec** [comment]
### Merge activity

* **Aug 27, 3:50 PM EDT**: @buffalojoec started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3134).

**Pull request merged**
