### PR TITLE
Add more request transformers

### PR DESCRIPTION
**Pull request by lorisleiva**
This PR finishes the refactoring of the `getDefaultRequestTransformerForSolanaRpc` function by creating three new request transformers and delegating to them:

- `getIntegerOverflowRequestTransformer`: Wraps the integer overflow visitor in a request transformer.
- `getBigIntDowncastRequestTransformer`: Wraps the bigint downcast visitor in a request transformer.
- `getTreeWalkerRequestTransformer`: Helper that creates request transformers from visitors.

Additionally, this PR changes the definition of the `onIntegerOverflow` slightly by using `request: RpcRequest` as its first argument instead of `methodName: string` to be more consistent with the rest of the RPC API.

### CODE REVIEW

**Comment by lorisleiva** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3161?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#3161** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3161?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#3160** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3160?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3159** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3159?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3158** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3158?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3150** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3150?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3149** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3149?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3148** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3148?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3147** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3147?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3146** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3146?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#3145** <a href="https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3145?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lorisleiva and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by buffalojoec — COMMENTED** [review]
I think it would make more sense for this PR to be two separate PRs. You've got a pretty clear distinction between the two in both the changeset and the READMEs.

**Comment by lorisleiva** [comment]
@buffalojoec Yeah I should have done but because I'm renaming filenames in this PR, running `gt split` is a nightmare to resolve. 😔

**Review by steveluscher — APPROVED** [review]
Added via Giphy

**Comment by lorisleiva** [comment]
### Merge activity

* **Sep 1, 2:06 PM EDT**: @lorisleiva started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/solana-labs/solana-web3.js/3161).

**Pull request merged**
