### PR TITLE
Revert "chore: bump @babel/plugin-transform-runtime from 7.22.9 to 7.…

### PR DESCRIPTION
**Pull request by 2501babe**
…22.10 (#1561)"

This reverts commit d6c3cfe44a9c2f5a4be006035e85fdc813d158f0.

### CODE REVIEW

**Comment by 2501babe** [comment]
cc @buffalojoec lets see if this passes

**Comment by 2501babe** [comment]
oh lame maybe not

**Comment by 2501babe** [comment]
the last babel-core update was a month ago, so it cant possibly be that. idk

**Comment by buffalojoec** [comment]
ahh nuts. You are thinking it was one of these bumps?

**Pull request closed without merging**
